alphabet   = 'rwuhaqynetlgiofvmxpszkbcqd'
subKey = "abcdefghijklmnopqrstuvwxyz"


txt="jdiaiirmtjtipiaeknjdiabikkitjewkmtdizdmldtxdnnkxnqscjiatixcamjgxnqsijmjmnhtmhxkczmhlxgwiasejamnjehzctxgwiaxdekkihlijditixnqsijmjmnhtonxctsamqeamkgnhtgtjiqtezqmhmtjaejmnhochzeqihjektbdmxdeaipiagctiockehzqeavijewkitvmkktdnbipiabiwikmipijdisansiascasntinoedmldtxdnnkxnqscjiatixcamjgxnqsijmjmnhmthnjnhkgjnjiexdpekcewkitvmkktwcjektnjnlijtjczihjtmhjiaitjizmhehzirxmjizewncjxnqscjiatxmihxizioihtmpixnqsijmjmnhteainojihkewnamncteooematehzxnqiznbhjnachhmhlxdixvkmtjtehzirixcjmhlxnhomltxamsjtnooihtinhjdinjdiadehzmtdiepmkgonxctiznhirsknaejmnhehzmqsanpmtejmnhehznojihdetikiqihjtnoskegbiwikmipiexnqsijmjmnhjncxdmhlnhjdinooihtmpiikiqihjtnoxnqscjiatixcamjgmtjdiaionaiewijjiapidmxkionajixdipehlikmtqjntjczihjtmheqiamxehdmldtxdnnktocajdiabiwikmipijdejehchziatjehzmhlnonooihtmpijixdhmfcitmtittihjmekonaqnchjmhlehiooixjmpizioihtiehzjdejjdijnnktehzxnhomlcaejmnhonxctihxnchjiaizmhzioihtmpixnqsijmjmnhtznithnjkieztjczihjtjnvhnbjdimaihiqgetiooixjmpikgetjiexdmhljdiqjnexjmpikgjdmhvkmviehejjexviasmxnxjomtehnooihtmpikgnamihjizdmldtxdnnkxnqscjiatixcamjgxnqsijmjmnhjdejtiivtjnlihiaejimhjiaitjmhxnqscjiatxmihxieqnhldmldtxdnnkiatjiexdmhljdiqihncldewncjxnqscjiatixcamjgjnsmfcijdimaxcamntmjgqnjmpejmhljdiqjnirsknainhjdimanbhehzihewkmhljdiqjnwijjiazioihzjdimaqexdmhitjdiokelmtsmxnXJO{H6A4Q_4H41G515_15_73Z10C5_6XO50W5X}".lower()

flagThing = "smxnXJO{H6A4Q_4H41G515_15_73Z10C5_6XO50W5X}"

#s = p
#m = i
#x = c
#n = o

outText = ''
for x in txt:
  if(x in subKey):
    outText += alphabet[subKey.index(x)]
  else:
      outText += '\033[1;31;40m' + x
print(outText)
